-- MySQL Script generated by MySQL Workbench
-- 02/06/17 21:49:18
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dingofbdev
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dingofbdev
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dingofbdev` DEFAULT CHARACTER SET utf8 ;
USE `dingofbdev` ;

-- -----------------------------------------------------
-- Table `dingofbdev`.`concours`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dingofbdev`.`concours` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(60) NOT NULL,
  `date_debut` DATE NULL,
  `heure_debut` TIME NULL,
  `date_fin` DATE NULL,
  `heure_fin` TIME NULL,
  `accueil` TEXT(255) NULL,
  `reglement` TEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dingofbdev`.`lots`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dingofbdev`.`lots` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(60) NULL,
  `url` VARCHAR(255) NULL,
  `description` VARCHAR(255) NULL,
  `concours_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_lots_concours1_idx` (`concours_id` ASC),
  CONSTRAINT `fk_lots_concours1`
    FOREIGN KEY (`concours_id`)
    REFERENCES `dingofbdev`.`concours` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dingofbdev`.`styles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dingofbdev`.`styles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `theme` VARCHAR(45) NULL,
  `bg_home` VARCHAR(45) NULL,
  `bg_default` VARCHAR(45) NULL,
  `color_button` VARCHAR(45) NULL,
  `font_color` VARCHAR(45) NULL,
  `font_family` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dingofbdev`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dingofbdev`.`users` (
  `id_fb` VARCHAR(255) NOT NULL,
  `nom` VARCHAR(45) NULL,
  `prenom` VARCHAR(45) NULL,
  `mail` VARCHAR(255) NULL,
  `token` VARCHAR(255) NULL,
  `banni` TINYINT(1) NULL,
  PRIMARY KEY (`id_fb`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dingofbdev`.`participation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dingofbdev`.`participation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `source_photo` VARCHAR(255) NULL,
  `concours_id` INT NOT NULL,
  `users_id_fb` VARCHAR(255) NOT NULL,
  `signalement` TINYINT(1) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_participation_concours1_idx` (`concours_id` ASC),
  INDEX `fk_participation_users1_idx` (`users_id_fb` ASC),
  CONSTRAINT `fk_participation_concours1`
    FOREIGN KEY (`concours_id`)
    REFERENCES `dingofbdev`.`concours` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_participation_users1`
    FOREIGN KEY (`users_id_fb`)
    REFERENCES `dingofbdev`.`users` (`id_fb`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dingofbdev`.`vote`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dingofbdev`.`vote` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_voteur` VARCHAR(255) NULL,
  `participation_idparticipation` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_vote_participation1_idx` (`participation_idparticipation` ASC),
  CONSTRAINT `fk_vote_participation1`
    FOREIGN KEY (`participation_idparticipation`)
    REFERENCES `dingofbdev`.`participation` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dingofbdev`.`administration`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dingofbdev`.`administration` (
  `cgu` TEXT NULL,
  `mentions_legales` TEXT NULL)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
